name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
      app:
        description: "Application to deploy"
        required: true
        type: choice
        options:
          - both
          - ui
          - api
        default: "both"
  # push:
  #   branches: [main]

jobs:
  deploy-ui:
    if: ${{ github.event.inputs.app == 'ui' || github.event.inputs.app == 'both' }}
    runs-on: [ self-hosted, ubuntu-4gb-hel1-1 ]
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      # - name: Cleanup Docker
      #   run: |
      #     docker image prune -af
      #     docker builder prune -af
      - name: Build .env
        run: printf '%s' ${{ toJSON(vars.UI_ENV_FILE) }} | python3 -c "import sys,json; sys.stdout.write(json.load(sys.stdin))" > apps/ui/.devcontainer/mapped/.env
      # - name: Deploy UI
      #   run: |
      #     set -euo pipefail
      #     cd apps/ui/.devcontainer/mapped
      #     docker compose down
      #     docker compose up --build -d --wait
      #     bash cmd-run.sh

  deploy-api:
    if: ${{ github.event.inputs.app == 'api' || github.event.inputs.app == 'both' }}
    runs-on: [ self-hosted, ubuntu-4gb-hel1-1 ]
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      # - name: Cleanup Docker
      #   run: |
      #     docker image prune -af
      #     docker builder prune -af
      - name: Build .env
        run: printf '%s' ${{ toJSON(vars.API_ENV_FILE) }} | python3 -c "import sys,json; sys.stdout.write(json.load(sys.stdin))" > apps/api/.devcontainer/mapped/.env
      # - name: Deploy API
      #   run: |
      #     set -euo pipefail
      #     cd apps/api/.devcontainer/mapped
      #     docker compose down
      #     docker compose up --build -d --wait
      #     bash cmd-run.sh
